name: frontend CI (hugo)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hugo-build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
      - name: Build
        run: hugo --logLevel debug --printMemoryUsage --printI18nWarnings --printUnusedTemplates --source ./frontend
